### ISSUE TITLE
build fails with python 3.11.0a1

### ISSUE THREAD

**Issue by opoplawski** [tlsfuzzer/python-ecdsa#268]
python-ecdsa fails to build with Python 3.11.0a1.
```
Traceback (most recent call last):
  File "/builddir/build/BUILD/ecdsa-0.17.0/setup.py", line 19, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/ecdsa-0.17.0/versioneer.py", line 1538, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/ecdsa-0.17.0/versioneer.py", line 1465, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/ecdsa-0.17.0/versioneer.py", line 346, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```
Removed from the configparser module: the SafeConfigParser class, the filename
property of the ParsingError class, the readfp() method of the ConfigParser
class, deprecated since Python 3.2. (Contributed by Hugo van Kemenade in
bpo-45173.)
https://docs.python.org/3.11/whatsnew/3.11.html

**Comment by tomato42** [comment]
Thanks for the report, looks like we'll need to extend CI to both 3.10 and 3.11a.
I'll try fixing it before 0.18.0 release, but can't provide a schedule for this.

**Comment by hroncok** [comment]
Updating the bundled versioneer should fix this.

**Comment by tomato42** [comment]
> Updating the bundled versioneer should fix this.

Turns out it's not so simple. versioneer dropped support for python 2 and <3.5, so the generated file needs to be modified.
Secondly, the python itself crashes when running the test suite on py3.11a3: https://github.com/tlsfuzzer/python-ecdsa/runs/4702997032?check_suite_focus=true#step:23:95
